name: Xiliary Releng Workflow
on:
  push:
    branches:    
      - '!**'
      - 'master'
      - 'development'
jobs:
  build-on-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache local Maven and P2 repositories
        uses: actions/always-upload-cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.p2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.6.3
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -f ${{ github.workspace }}/com.codeaffine.xiliary.releng/pom.xml clean compile
        
